const express = require("express");
const cors = require("cors");
require("dotenv").config();
const app = express();
const acomodacionesRoutes = require("../routes/acomodacionesRoutes");
const authRoutes = require("../routes/configRoutes");
const checkinRoutes = require("../routes/checkinRoutes");
const calculoReservaRoutes = require("../routes/calculoReservaRoutes");
const habitacionesRoutes = require("../routes/habitacionesRoutes");
const entidadesRoutes = require("../routes/entidadesRoutes");
const asignacionHabitacionRoutes = require("../routes/asignacionHabitacionRoutes");
const personaRoutes = require("../routes/personaRoutes");
const recaudoRoutes = require("../routes/recaudoRoutes");
const tarifaRoutes = require("../routes/tarifaRoutes");
const swaggerUi = require("swagger-ui-express");
const swaggerSpec = require("../docs/swagger");
const reservaRoutes = require("../routes/reservaRoutes");
const inventarioRoutes = require("../routes/inventarioRoutes");
const pedidosAsignacionRoutes = require("../routes/pedidosAsignacionRoutes");
const bodegasRoutes = require("../routes/bodegaRoutes");
const cargosRoutes = require("../routes/cargoRoutes");
const checkOutRoutes = require("../routes/checkOutsRoutes");
const reporteRoutes = require("../routes/reporteRoutes");
const cierreDiarioRoutes = require("../cierre-diario/cierreDiarioRoutes");
app.use(cors());
app.use(express.json());
app.use("/cierre-diario", cierreDiarioRoutes);
app.use("/reporte", reporteRoutes);
app.use("/checkout", checkOutRoutes);
app.use("/auth", authRoutes);
app.use("/cargo", cargosRoutes);
app.use("/check-in", checkinRoutes);
app.use("/tarifa", tarifaRoutes);
app.use("/acomodacion", acomodacionesRoutes);
app.use("/recaudo", recaudoRoutes);
app.use("/persona", personaRoutes);
app.use("/habitacion", habitacionesRoutes);
app.use("/habitacion", asignacionHabitacionRoutes);
app.use("/entidad", entidadesRoutes);
app.use("/api-docs", swaggerUi.serve, swaggerUi.setup(swaggerSpec));
app.use("/reserva", calculoReservaRoutes);
app.use("/reserva", reservaRoutes);
app.use("/inventario", inventarioRoutes);
app.use("/pedidos-habitacion", pedidosAsignacionRoutes);
app.use("/bodegas", bodegasRoutes);
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`Servidor corriendo en puerto ${PORT}`);
  console.log(`Swagger disponible en http://localhost:${PORT}/api-docs`);
});
