const express = require("express");
const cors = require("cors");
require("dotenv").config();
const app = express();
const acomodacionesRoutes = require("./acomodaciones/acomodacion.routes");
const authRoutes = require("./configuracion/config-auth/config.routes");
const checkinRoutes = require("./checkIn/checkin.routes");
const calculoReservaRoutes = require("./calculo-reserva/calculoreserva.routes");
const habitacionesRoutes = require("./habitaciones/habitacion.routes");
const entidadesRoutes = require("./configuracion/entidades/entidad.routes");
const asignacionHabitacionRoutes = require("./habitaciones/asignacion/asignacionhabitacion.routes");
const personaRoutes = require("./personas/persona.routes");
const recaudoRoutes = require("./recaudos/recaudo.routes");
const tarifaRoutes = require("./tarifas/tarifa.routes");
const swaggerUi = require("swagger-ui-express");
const swaggerSpec = require("./docs/swagger");
const reservaRoutes = require("./reserva/reserva.routes");
const inventarioRoutes = require("./inventario/inventario.routes");
const pedidosAsignacionRoutes = require("./pedidos/pedidosasignacion.routes");
const bodegasRoutes = require("./bodega/bodega.routes");
const cargosRoutes = require("./cargos/cargo.routes");
const checkOutRoutes = require("./checkout/checkout.routes");
const reporteRoutes = require("./reportes/reportes.routes");
const cierreDiarioRoutes = require("./cierre-diario/cierrediario.routes");
app.use(cors());
app.use(express.json());
app.use("/cierre-diario", cierreDiarioRoutes);
app.use("/reporte", reporteRoutes);
app.use("/checkout", checkOutRoutes);
app.use("/auth", authRoutes);
app.use("/cargo", cargosRoutes);
app.use("/check-in", checkinRoutes);
app.use("/tarifa", tarifaRoutes);
app.use("/acomodacion", acomodacionesRoutes);
app.use("/recaudo", recaudoRoutes);
app.use("/persona", personaRoutes);
app.use("/habitacion", habitacionesRoutes);
app.use("/habitacion", asignacionHabitacionRoutes);
app.use("/entidad", entidadesRoutes);
app.use("/api-docs", swaggerUi.serve, swaggerUi.setup(swaggerSpec));
app.use("/reserva", calculoReservaRoutes);
app.use("/reserva", reservaRoutes);
app.use("/inventario", inventarioRoutes);
app.use("/pedidos-habitacion", pedidosAsignacionRoutes);
app.use("/bodegas", bodegasRoutes);
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`Servidor corriendo en puerto ${PORT}`);
  console.log(`Swagger disponible en http://localhost:${PORT}/api-docs`);
});
